version: "3.1"

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: vin_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example

  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - .:/app
    ports:
      - 8000:8000
    environment:
      POSTGRES_DB: vin_test
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: example
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
